import sqlite3

conn = sqlite3.connect("local.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS DISPUTE (
    ENFORCEMENT_ID TEXT PRIMARY KEY,
    GOV_NAME TEXT,
    GOV_RESULT TEXT,
    GOV_UPDATE_DATE TIMESTAMP
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS UPDATE_LOG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ENFORCEMENT_ID TEXT,
    GOV_NAME TEXT,
    GOV_RESULT TEXT,
    STATUS TEXT,
    ERROR_MESSAGE TEXT,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")

cursor.execute("INSERT OR IGNORE INTO DISPUTE (ENFORCEMENT_ID) VALUES ('EFM00001')")
cursor.execute("INSERT OR IGNORE INTO DISPUTE (ENFORCEMENT_ID) VALUES ('EFM00002')")

conn.commit()
conn.close()
